export const ProjectConstants = {
  PROJECT_GET_ALL: 'PROJECT_GET_ALL',
  PROJECT_SAVE_ALL: 'PROJECT_SAVE_ALL',
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_GET_ALL_TEAM: 'PROJECT_GET_ALL_TEAM',
  PROJECT_SAVE_ALL_TEAM: 'PROJECT_SAVE_ALL_TEAM',
  PROJECT_GET_A: 'PROJECT_GET_A',
  PROJECT_SAVE_A: 'PROJECT_SAVE_A',
};
