export const TasksConstants = {
  TASKS_GET_ALL: 'TASKS_GET_ALL',
  TASKS_ALL: 'TASKS_ALL',
  TASKS_SAVE: 'TASKS_SAVE',
  TASKS_ADD_COLUMN: 'TASKS_ADD_COLUMN',
  TASKS_GET_LOGS: 'TASKS_GET_LOGS',
  TASKS_SAVE_LOGS: 'TASKS_SAVE_LOGS',
};
